# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180821_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(default=1, max_length=32, verbose_name='图标'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default=1, max_length=32, verbose_name='菜单'),
            preserve_default=False,
        ),
    ]
